language: php
php:
  - 7.2
  - 7.3
before_script:
  - composer require php-coveralls/php-coveralls
script:
  - phpunit --coverage-clover build/coverage/clover.xml
after_script:
  - php vendor/bin/php-coveralls -v
