language: php
php:
  - 7.2
  - 7.3
before_script:
  - composer install
  - composer update satooshi/php-coveralls
script:
    - ant coverage
after_script:
    - php vendor/bin/coveralls -v -c .coveralls.yml
