language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3  
  - nightly
matrix:
  include:
    - dist: trusty
      php: hhvm
      sudo: required
  allow_failures:
    - php: nightly
before_script:
  - composer install --dev
  - composer update satooshi/php-coveralls --dev
script:
    - ant coverage
after_script:
    - php vendor/bin/coveralls -v -c .coveralls.yml
